export const themeJson = {
  cssVariables: {
    "general-backcolor": "rgba(255, 255, 255, 1)",
    "general-backcolor-dark": "rgba(248, 248, 248, 1)",
    "general-backcolor-dim": "rgba(243, 243, 243, 1)",
    "general-backcolor-dim-light": "rgba(249, 249, 249, 1)",
    "general-backcolor-dim-dark": "rgba(243, 243, 243, 1)",
    "general-forecolor": "rgba(0, 0, 0, 0.91)",
    "general-forecolor-light": "rgba(0, 0, 0, 0.45)",
    "general-dim-forecolor": "rgba(0, 0, 0, 0.91)",
    "general-dim-forecolor-light": "rgba(0, 0, 0, 0.45)",
    "primary-backcolor": "rgba(25, 179, 148, 1)",
    "primary-backcolor-light": "rgba(25, 179, 148, 0.1)",
    "primary-backcolor-dark": "rgba(20, 164, 139, 1)",
    "primary-forecolor": "rgba(255, 255, 255, 1)",
    "primary-forecolor-light": "rgba(255, 255, 255, 0.25)",
    "base-unit": "8px",
    "corner-radius": "4px",
    "secondary-backcolor": "rgba(255, 152, 20, 1)",
    "secondary-backcolor-light": "rgba(255, 152, 20, 0.1)",
    "secondary-backcolor-semi-light": "rgba(255, 152, 20, 0.25)",
    "secondary-forecolor": "rgba(255, 255, 255, 1)",
    "secondary-forecolor-light": "rgba(255, 255, 255, 0.25)",
    "shadow-small": "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
    "shadow-medium": "0px 2px 6px 0px rgba(0, 0, 0, 0.1)",
    "shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.1)",
    "shadow-inner": "inset 0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
    "border-light": "rgba(0, 0, 0, 0.09)",
    "border-default": "rgba(0, 0, 0, 0.16)",
    "border-inside": "rgba(0, 0, 0, 0.16)",
    "special-red": "rgba(229, 10, 62, 1)",
    "special-red-light": "rgba(229, 10, 62, 0.1)",
    "special-red-forecolor": "rgba(255, 255, 255, 1)",
    "special-green": "rgba(25, 179, 148, 1)",
    "special-green-light": "rgba(25, 179, 148, 0.1)",
    "special-green-forecolor": "rgba(255, 255, 255, 1)",
    "special-blue": "rgba(67, 127, 217, 1)",
    "special-blue-light": "rgba(67, 127, 217, 0.1)",
    "special-blue-forecolor": "rgba(255, 255, 255, 1)",
    "special-yellow": "rgba(255, 152, 20, 1)",
    "special-yellow-light": "rgba(255, 152, 20, 0.1)",
    "special-yellow-forecolor": "rgba(255, 255, 255, 1)",
    "article-font-xx-large-fontSize": "64px",
    "article-font-xx-large-textDecoration": "none",
    "article-font-xx-large-fontWeight": "700",
    "article-font-xx-large-fontStyle": "normal",
    "article-font-xx-large-fontStretch": "normal",
    "article-font-xx-large-letterSpacing": "0",
    "article-font-xx-large-lineHeight": "64px",
    "article-font-xx-large-paragraphIndent": "0px",
    "article-font-xx-large-textCase": "none",
    "article-font-x-large-fontSize": "48px",
    "article-font-x-large-textDecoration": "none",
    "article-font-x-large-fontWeight": "700",
    "article-font-x-large-fontStyle": "normal",
    "article-font-x-large-fontStretch": "normal",
    "article-font-x-large-letterSpacing": "0",
    "article-font-x-large-lineHeight": "56px",
    "article-font-x-large-paragraphIndent": "0px",
    "article-font-x-large-textCase": "none",
    "article-font-large-fontSize": "32px",
    "article-font-large-textDecoration": "none",
    "article-font-large-fontWeight": "700",
    "article-font-large-fontStyle": "normal",
    "article-font-large-fontStretch": "normal",
    "article-font-large-letterSpacing": "0",
    "article-font-large-lineHeight": "40px",
    "article-font-large-paragraphIndent": "0px",
    "article-font-large-textCase": "none",
    "font-medium-fontSize": "24px",
    "article-font-medium-textDecoration": "none",
    "article-font-medium-fontWeight": "700",
    "article-font-medium-fontStyle": "normal",
    "article-font-medium-fontStretch": "normal",
    "article-font-medium-letterSpacing": "0",
    "article-font-medium-lineHeight": "32px",
    "article-font-medium-paragraphIndent": "0px",
    "article-font-medium-textCase": "none",
    "article-font-default-fontSize": "16px",
    "article-font-default-textDecoration": "none",
    "article-font-default-fontWeight": "400",
    "article-font-default-fontStyle": "normal",
    "article-font-default-fontStretch": "normal",
    "article-font-default-letterSpacing": "0",
    "article-font-default-lineHeight": "28px",
    "article-font-default-paragraphIndent": "0px",
    "article-font-default-textCase": "none",
  },
  isPanelless: false,
};
