import { Button, Grid, Typography } from "@material-ui/core";
import { Card, Slider, CardActionArea, IconButton } from "@mui/material";
import React from "react";
import CandidateOverviewDialogue from "./CandidateOverviewDialogue";
import "./style.css";
import AutogeneratedCV from "components/AutogeneratedCV";
import { PDFDownloadLink } from "@react-pdf/renderer";
import { Download } from "@mui/icons-material";
import candids from "../../assets/final.jsx"

function ViewFinalCandidates() {

  const candidsTemp = [
    {
      firstName: "Mariz",
      lastName: "Awad",
      email: "mariz.awad97@gmail.com",
      QAs: [
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
      ],
      score: 80,
      seniority: 4,
    },
    {
      firstName: "Mariz",
      lastName: "Awad",
      email: "mariz.awad97@gmail.com",
      QAs: [
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
      ],
      score: 20,
      seniority: 1,
    },
    {
      firstName: "Mariz",
      lastName: "Awad",
      email: "mariz.awad97@gmail.com",
      QAs: [
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
        {
          question:
            "Describe a time when you had to deal with a difficult coworker or team member. How did you handle the situation, and what was the outcome?",
          answer:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        },
      ],
      score: 70,
      seniority: 3,
    },
  ];
  
  const [showCandidateOverview, toggleShowCandidateOverview] =
    React.useState(false);
  const ThumbComponent = (props) => {
    return <span className="custom-thumb" {...props} />;
  };
  return (
    <Grid container direction={"column"}>
      {candids.sort((a, b) => b.similarity_score - a.similarity_score).map((elem, key) => {
        return (
          <Grid item xs={6}>
            <Card style={{ padding: "50px" }}>
              <CardActionArea onClick={() => toggleShowCandidateOverview(true)}>
                <Grid container>
                  <Grid item xs={6}>
                    <Typography
                      variant="body1"
                      align="left"
                      style={{ color: "black" }}
                    >
                      <strong>
                        ({key + 1}) {elem.more_info.main_info.Name}
                      </strong>

                       {/* @ts-ignore */}
                      <PDFDownloadLink
                        document={<AutogeneratedCV />}
                        // fileName={`${name}_interview_answers.pdf`}
                        fileName={`interview_answers.pdf`}
                      >
                        {({ blob, url, loading, error }) =>
                          loading ? (
                            "Loading document..."
                          ) : (
                            <IconButton
                              style={{ color: "black" }}
                              aria-label="Save PDF"
                            >
                              <Download />
                                 
                            </IconButton>
                          )
                        }
                      </PDFDownloadLink>
                    </Typography>
                  </Grid>
                  <Grid item xs={6}>
                    <Typography
                      variant="body2"
                      align="right"
                      style={{ color: "black" }}
                    >
                      <strong>Seniority Level: {elem.experience_info.seniority_level}</strong>
                    </Typography>
                  </Grid>
                </Grid>

                <Typography variant="body2" align="left">
                  {elem.experience_info.reason}
                </Typography>
                <br />
                <br />
                <Slider
                  className="gradient-background"
                  valueLabelDisplay="on"
                  defaultValue={elem.similarity_score*100}
                  valueLabelFormat={Math.round(elem.similarity_score*100*10)/10 + "%"}
                  style={{
                    pointerEvents: "none",
                    color: "linen",

                    // color:
                    // elem.score > 70
                    //   ? "#AAFF00"
                    //   : elem.score < 30
                    //   ? "#FF2400"
                    //   : "#FAFA33",

                    /* Replace #ff0000 and #00ff00 with your desired gradient colors */
                  }}
                ></Slider>
              </CardActionArea>
            </Card>
          </Grid>
        );
      })}
      {showCandidateOverview && <CandidateOverviewDialogue />}
    </Grid>
  );
}

export default ViewFinalCandidates;
